major changes: add band numbers and types to pass along to scripts instead of image type. remove all caps from echo text to user. change filename creation in band_math to be user generated.

diff --git a/geomundo b/geomundo
--- a/geomundo
+++ b/geomundo
@@ -1,4 +1,5 @@
 #!/bin/bash
+source helper_functions
 
 clear # clear terminal window
 echo  '                                              _         '
@@ -21,7 +22,7 @@ echo "* @source   : AUTOMATED GEOPROCESSING - IMAGE_MASTER          *"
 echo "* @tool     : VHR RESOLUTION IMAGE PROCESSING                 *"
 echo "* @autor    : CHRISTOPHER TURNER                              *"
 echo "* @e-mail   : CLTURNER23@gmail.com                            *"
-echo "* @revision : 0.0 - 29/11/2018                                *"
+echo "* @revision : 0.0 - 10/08/2023                                *"
 echo "* ............................................................*"
 echo "***************************************************************"
 echo
@@ -36,8 +37,10 @@ else
 fi
 
 # Function to request the absolute path for the output directory
+# If not a DIR call get_output_dir again
 get_output_dir () {
-    echo PLEASE ENTER THE ABSOLUTE PATH TO YOUR PREFERED OUTPUT DIRECTORY
+    echo
+    echo Please enter the absolute path to your preferred output directory
     echo
     read OUTPUT_DIR
     if [ -d $OUTPUT_DIR ]
@@ -45,20 +48,22 @@ get_output_dir () {
 	OUTPUT_DIR=$OUTPUT_DIR
     else
 	echo
-	echo THAT WAS NOT AN EXSISTING DIRECTORY
+	echo That was not an existing directory
 	get_output_dir
     fi
 }
 
 # Function to get the image type from the user
+#  Call get_image_type if not a choice in menu
 get_image_type () {
-    clear
-    echo "WHAT TYPE OF IMAGE WOULD YOU LIKE TO PROCESS"
-    echo "1. PERU SAT"
-    echo "2. PLANET"
-    echo "3. WORLDVIEW"
-    echo "4. GEOEYE"
-    echo "5. SENTINEL"
+    echo
+    echo "What type of image would you like to process"
+    echo "1. Peru Sat"
+    echo "2. Planet"
+    echo "3. Worldview"
+    echo "4. Geoeye"
+    echo "5. Sentinel"
+    echo "6. Custom"
     echo
     echo "Choose and image type and press [ENTER]:"
     read IMAGE_TYPE
@@ -67,157 +72,162 @@ get_image_type () {
     then
 	IMAGE_TYPE=$IMAGE_TYPE
     else
-	clear
+	echo
 	echo THAT WAS NOT AN IMAGE CHOICE
 	echo
 	get_image_type
     fi
 
-    # Change image type to text for future file names
+    BAND_PAN=0
+    BAND_BLUE=0
+    BAND_GREEN=0
+    BAND_RED=0
+    BAND_NIR=0
+    BAND_CA=0
+    BAND_RE=0
+    BAND_SWIR=0
+
+        # Check for image type and set corresponding variables for bands
     if [ "$IMAGE_TYPE" = 1 ]; then
-	IMAGE_TYPE="PSAT"
+        IMAGE_TYPE="PSAT"
+        BAND_PAN=1
+        BAND_BLUE=2
+        BAND_GREEN=3
+        BAND_RED=4
+        BAND_NIR=5
     elif [ "$IMAGE_TYPE" = 2 ]; then
-	IMAGE_TYPE="PLNT"
+        IMAGE_TYPE="PLNT"
+        BAND_BLUE=1
+        BAND_GREEN=2
+        BAND_RED=3
+        BAND_NIR=4
     elif [ "$IMAGE_TYPE" = 3 ]; then
-	IMAGE_TYPE="WVIW"
+        IMAGE_TYPE="WVIW"
+        BAND_PAN=1
+        BAND_BLUE=2
+        BAND_GREEN=3
+        BAND_RED=4
+        BAND_NIR=5
     elif [ "$IMAGE_TYPE" = 4 ]; then
-	IMAGE_TYPE="GEYE"
+        IMAGE_TYPE="GEYE"
+        BAND_PAN=1
+        BAND_BLUE=2
+        BAND_GREEN=3
+        BAND_RED=4
+        BAND_NIR=5
     elif [ "$IMAGE_TYPE" = 5 ]; then
-	IMAGE_TYPE="SENT"
+        IMAGE_TYPE="SENT"
+        BAND_CA=1
+        BAND_BLUE=2
+        BAND_GREEN=3
+        BAND_RED=4
+        BAND_RE=5
+        BAND_NIR=6
+        BAND_SWIR=7
+    elif [ "$IMAGE_TYPE" = 6 ]; then
+        IMAGE_TYPE="CUSTOM"
+        # Set your custom band variables
+        get_band_numbers
     fi
-    clear
+
 }
 
 # Get the the process or processes requested by the user
 get_process_string () {
-echo CHOOSE A PROCESS
-echo
-echo PLEASE CHOOSE A PROCESS
-echo
-echo EXAMPLE: 1 3 7
-echo
-echo " 1. ADD RADIO METRIC INDICES"
-echo " 2. ADD BY BAND MATH (ADD A BAND TO AN IMAGE)"
-echo " 3. BAND MATH (CREATE A SINGLE BAND IMAGE)"
-echo " 4. REMOVE BANDS"
-echo " 5. CONCATENATE"
-echo " 6. LARGE SCALE MEAN SHIFT"
-echo " 7. MOSAIC"
-echo " 8. EXTRACT ROI (REGION OF INTEREST)"
-echo " 9. UNZIP FILES"
-echo "10. CLOUD DETECTOR"
-echo "11. MINES ROADS & DEFORESTATION WORKFLOW"
-echo "12. MINES ROADS & DEFORESTATION ROI WORKFLOW"
-echo
-read PROCESS
+    echo
+    echo Please choose a process or processes
+    echo
+    echo "To add a Radiometric Indice layer, a custom layer with band math and"
+    echo "  a extract a Region of interest"
+    echo EXAMPLE: 1 3 8 
+    echo
+    echo "1. Add radiometric indices."
+    echo "2. Add by band math (add a band to an image)."
+    echo "3. Band math (create a single-band image)."
+    echo "4. Remove bands."
+    echo "5. Concatenate."
+    echo "6. Large-scale mean shift."
+    echo "7. Mosaic."
+    echo "8. Extract ROI (region of interest)."
+    echo "9. Unzip files."
+    echo "10. Cloud detector."
+    echo "11. Mines, roads, and deforestation workflow."
+    echo "12. Mines, roads, and deforestation ROI workflow."
+    echo
+    read -ra PROCESS_ARR
 
-# If user presses enter without gioving a process
-if [ -z $PROCESS ];
-then
-    clear
-    echo YOU DID NOT ENTER A PROCESS
-    echo
-    echo PLEASE ENTER A NUMBER OR NUMBERS CORRESPONDING TO A PROCESSES
-    echo
-    echo EXAMPLE 1 3 7
-    echo
-    get_process_string
-else
-    # Loop the process string entered by the user
-    for num in $(echo $PROCESS | sed "s/%/ /g");
-    do
-	# Check if any value in process string is char and not a number
-	# If incorrect value given ask user create a new process string
-        re='[a-zA-Z]'
-	if [[ "$num" =~ $re ]];
-	then
-	    clear
-	    PROCESS=$( echo $PROCESS | tr "%" " " )
-	    echo THE ENTRY $num IN YOUR PROCESS STRING, $PROCESS, DOES NOT CORRESPOND TO A PROCESS
-	    echo
-	    echo PLEASE ENTER ONLY A NUMBER OR NUMBERS CORRESPONDING TO A PROCESSES
-	    echo
-	    get_process_string
-	# Check if number in process string corresponds to a process
-        # If incorrect value given ask user create a new process string
-        elif [ "$num" -lt 1 ] || [ "$num" -gt 12 ];
-        then
-	    clear
-	    PROCESS=$( echo $PROCESS | tr "%" " " )
-            echo YOU ENTERED $num INTO YOUR PROCESS STRING $PROCESS
-	    echo
-	    echo PLEASE ENTER ONLY A NUMBER OR NUMBERS CORRESPONDING TO A PROCESSES
-	    echo
-	    get_process_string
+     # Check if the user provided any input
+    if [ "${#PROCESS_ARR[@]}" -eq 0 ]; then
+        clear
+        echo "YOU DID NOT ENTER ANY PROCESSES"
+        echo "PLEASE ENTER ONE OR MORE NUMBERS CORRESPONDING TO PROCESSES"
+        get_process_string
+    fi
+
+    # Loop through the user input and check if all values are within the range 1-12
+    for num in "${PROCESS_ARR[@]}"; do
+        if ! [[ "$num" =~ ^[1-9]$|^1[0-2]$ ]]; then
+            echo
+            echo "INVALID INPUT: $num"
+            echo "PLEASE ENTER NUMBERS BETWEEN 1 AND 12"
+            echo
+            get_process_string
         fi
     done
-    # Check if any of the process numbers are an automated workflow
-    # If there are no automated workflows in process string set $WORKFLOW=0
-    for num in $PROCESS;
-    do
-	if [ $num -eq 11 ] || [ $num -eq 12 ];
-	then
-            WORKFLOW=$num
-	    break
-	else
-            WORKFLOW=0
-	fi
-    done
-fi
-# Replaces spaces " " with "%" from the PROCESS variable so the chain
-#   can be succesfiully passed to the multiprocess file
-PROCESS=$( echo $PROCESS | tr " " "%" )
+
+    # Convert the array to a space-separated string for further processing
+    PROCESS=$(printf "%s " "${PROCESS_ARR[@]}")
+    # Replaces spaces " " with "%" from the PROCESS variable so the chain
+    #   can be succesfiully passed to the multiprocess file
+    PROCESS=$( echo $PROCESS | tr " " "%" )
 }
 
+get_image_paths () {
+    echo
+    echo "PLEASE ENTER THE ABSOLUTE PATH TO YOUR IMAGE/IMAGES OR A DIRECTORY OF FILES"
+    echo
+    read PATH_TO_IMAGES
+
+    if [[ -d $PATH_TO_IMAGES ]]; then
+        INPUT_DIR=$PATH_TO_IMAGES
+        for file in `ls $PATH_TO_IMAGES`; do
+            if [[ $file == *.tif* && $file != *tif.xml ]]; then
+                file_string="$file_string $PATH_TO_IMAGES/$file"
+            elif [[ $file == *.jp2* ]]; then
+                file_string="$file_string $PATH_TO_IMAGES/$file"
+            elif [[ $file == *.zip* && $PROCESS -eq 11 || $PROCESS -eq 12 ]] || [[ $PROCESS =~ 9 ]]; then
+                file_string="$file_string $PATH_TO_IMAGES/$file"
+            fi
+        done
+        PATH_TO_IMAGES=$file_string
+    else
+        INPUT_DIR="file_paths_were_entered_not_a_directory"
+    fi
+
+    char=" "
+    NUM_PATHS=$( echo "${PATH_TO_IMAGES}" | awk -F"${char}" '{print NF-1}' )
+    NUM_PATHS=$((NUM_PATHS+1))
+
+    PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr " " "%")
+}
+
+
 get_output_dir
+get_image_paths
 get_image_type
 get_process_string
 
-clear
-# IF PATH_TO_IMAGES IS A DIRECTORY: check that 1 or more tif are in directory
-echo
-echo PLEASE ENTER THE ABSOLUTE PATH TO YOUR IMAGE/IMAGES OR A DIRECTORY OF FILES
-echo
-read PATH_TO_IMAGES
 
-if [[ -d $PATH_TO_IMAGES ]]; then
-    INPUT_DIR=$PATH_TO_IMAGES
-    for file in `ls $PATH_TO_IMAGES`;
-    do
-        if [[ $file == *.tif* && $file != *tif.xml ]]; then
-            file_string="$file_string $PATH_TO_IMAGES/$file"
-	elif [[ $file == *.jp2* ]]; then
-	    file_string="$file_string $PATH_TO_IMAGES/$file"
-	elif  [[ $file == *.zip* && $PROCESS -eq 11 || $PROCESS -eq 12 ]] || [[ $PROCESS =~ 9 ]]; then
-	    file_string="$file_string $PATH_TO_IMAGES/$file"
-        fi
-    done
-    PATH_TO_IMAGES=$file_string
+# If not using an automated workflow set the WORKFLOW variable to 0
+if [ -z "$WORKFLOW" ]; then
+  WORKFLOW=0
 fi
-
-# Count the number of image paths from the Directory or the number of
-#    absolute image paths entered by the user
-char=" "
-NUM_PATHS=$( echo "${PATH_TO_IMAGES}" | awk -F"${char}" '{print NF-1}' )
-NUM_PATHS=$((NUM_PATHS+1))
-
-# Translate all spaces on image paths to % delimited string for  
-PATH_TO_IMAGES=$( echo $PATH_TO_IMAGES | tr " " "%")
 
 
 if [ $DEBUG = "d" ]; then
-    echo
-    echo $DEBUG
-    echo $OUTPUT_DIR
-    echo $INPUT_DIR
-    echo $IMAGE_TYPE
-    echo $PROCESS
-    echo $PATH_TO_IMAGES
-    echo $NUM_PATHS
-    echo $WORKFLOW
-    echo gemundo end
-    read sjkdjcodsg
+    get_debug "ending geomundo"
 fi
 
-# Pass all the user requirements to the multiprocess script
-multi_process $DEBUG $OUTPUT_DIR $INPUT_DIR $IMAGE_TYPE $PROCESS $PATH_TO_IMAGES $NUM_PATHS $WORKFLOW
+# Pass all the user requirements to the multiprocess script                                                                                                                                                   
+./multi_process "$DEBUG" "$OUTPUT_DIR" "$INPUT_DIR" "$IMAGE_TYPE" "$PROCESS" "$PATH_TO_IMAGES" "$NUM_PATHS" "$WORKFLOW" "$BAND_PAN" "$BAND_BLUE" "$BAND_GREEN" "$BAND_RED" "$BAND_NIR" "$BAND_CA" "$BAND_RE" "$BAND_SWIR"
+
